# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image and push
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
        # build docker
        # push docker => 100
        - task: Docker@2
          displayName: Build an and push an image
          inputs:
            containerRegistry: 'in28min-docker-hub'
            repository: 'bjacog/currency-exchange-devops'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'
        # copy Files to staging dir
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.yaml'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        # publish artifacts
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'manifests'
            publishLocation: 'Container'

# deply
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
# download artifacts
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
# image:100 => deply to k8s
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aws-kubernetes-cluster-service-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: bjacog/currency-exchange-devops:$(tag)
# apply deployment -- kubectl apply -f deloyment.yaml
